{
 "title": "bambulabs-exporter",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": { "query": "label_values(up,job)" } }
  ]
 },
 "panels": [
  { "title": "Instant Statuses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Print Percentage Remaining",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mc_percent{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nozzle Temperature (F) ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(nozzle_temper{job=\"$job\"})",
     "legendFormat": "Nozzle Temperature"
    },
    {
     "expr": "sum(nozzle_target_temper{job=\"$job\"})",
     "legendFormat": "Nozzle Target Temperature"
    }
   ]
  },
  {
   "title": "WiFi SIgnal in dBm",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wifi_signal{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AMS Temp",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 7, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "abs(sum(ams_temp{job=\"$job\"}))",
     "legendFormat": "AMS {{ ams_number }}"
    }
   ]
  },
  { "title": "Trending Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Up",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(up{job=\"bambulabs-exporter\"})",
     "legendFormat": "UP"
    }
   ]
  },
  {
   "title": "Remaining Time on Print",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "sum(mc_remaining_time{job=\"$job\"})",
     "legendFormat": "Print Job Timer"
    }
   ]
  },
  {
   "title": "AMS, Bed, & Chamber Temp",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "abs(sum(ams_temp{job=\"$job\"}))",
     "legendFormat": "AMS Temperature"
    },
    {
     "expr": "abs(sum(chamber_temper{job=\"$job\"}))",
     "legendFormat": "Chamber Temperature"
    }
   ]
  },
  {
   "title": "WiFi SIgnal",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "sum(wifi_signal{job=\"$job\"})",
     "legendFormat": "WiFi Signal"
    }
   ]
  },
  {
   "title": "Print Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "sum(print_error{job=\"$job\"})",
     "legendFormat": "Print Error"
    },
    {
     "expr": "sum(fail_reason{job=\"$job\"})",
     "legendFormat": "Failure Reason"
    },
    {
     "expr": "sum(mc_print_error_code{job=\"$job\"})",
     "legendFormat": "Print Error Code"
    }
   ]
  },
  {
   "title": "Nozzle Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum(nozzle_temper{job=\"$job\"})",
     "legendFormat": "Nozzle Temperature"
    },
    {
     "expr": "sum(nozzle_target_temper{job=\"$job\"})",
     "legendFormat": "Nozzle Target Temperature"
    }
   ]
  },
  {
   "title": "Fan Gear Metric",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "sum(fan_gear{job=\"$job\"})",
     "legendFormat": "Fan Gear"
    }
   ]
  },
  {
   "title": "Fan Speeds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "expr": "sum(big_fan1_speed{job=\"$job\"})",
     "legendFormat": "Big Fan 1"
    },
    {
     "expr": "sum(cooling_fan_speed{job=\"$job\"})",
     "legendFormat": "Cooling Fan"
    },
    {
     "expr": "sum(big_fan2_speed{job=\"$job\"})",
     "legendFormat": "Big Fan 2"
    }
   ]
  },
  {
   "title": "MC Print Stage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "sum(mc_print_sub_stage{job=\"$job\"})",
     "legendFormat": "Print Sub Stage"
    },
    {
     "expr": "sum(mc_print_stage{job=\"$job\"})",
     "legendFormat": "Print Stage"
    }
   ]
  }
 ]
}